on: [push]

name: install

jobs:
  install:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install packages.
        run: |
          install.packages("remotes")
          library(remotes)
          install_version("Rcpp", version = "1.0.13-1")
          install_version("RcppParallel", version = "5.1.9")
          install.packages(
            "stringfish",
            repos = "https://packagemanager.posit.co/cran/__linux__/noble/2025-06-02"
          )
        shell: Rscript {0}
      - name: Load stringfish.
        run: library(stringfish)
        shell: Rscript {0}
