on: [push]

name: reprex

jobs:
  reprex:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Install renv.
        run: install.packages("renv")
        shell: Rscript {0}
      - name: Restore packages.
        run: renv::restore()
        shell: Rscript {0}
